apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-imagens
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      type: pv-portfolio-api