# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Write Properties
      uses: christian-draeger/write-properties@1.0.1
      with:
        path: './src/main/resources/application.properties'
        property: 'spring.data.mongodb.uri'
        value: ${{ secrets.MONGO_URI }}
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - uses: actions/checkout@v2
      
    - run: mkdir -p configs
    
    - run: mv target/*.jar configs/.
    
    - uses: actions/upload-artifact@v2
      with:
        name: portfolio-configs
        path: configs
