# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Write Properties
      uses: christian-draeger/write-properties@1.0.1
      with:
        path: './src/main/resources/application.properties'
        mongo.uri.property: 'spring.data.mongodb.uri'
        mongo.uri.value: ${{ secrets.MONGO_URI }}
        mongo.database.property: 'spring.data.mongodb.uri'
        mongo.database.value: ${{ secrets.MONGO_DATABASE }}
    - name: Build with Maven
      run: mvn -B package --file pom.xml
